Make it possible to save current changes to some past revision and refactor main scripts
Signed-off-by: mimly <m.j.mlynczak@gmail.com>

diff --git a/git-join b/git-join
--- a/git-join
+++ b/git-join
@@ -3,6 +3,7 @@
 # shellcheck disable=SC1091,SC2034
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
@@ -11,10 +12,12 @@ set -o pipefail
 
 SCRIPT_DESCRIPTION="join revisions"
 SCRIPT_FULL_DESCRIPTION="-"
-SCRIPT_ARGUMENTS="[OPTION]... FROM..TO"
+SCRIPT_ARGUMENTS="[OPTION]... [FILE]..."
 SCRIPT_OPTIONS=(\
     "-d DATE, --date=DATE"\
     "-m MESSAGE, --message=MESSAGE"\
+    "-f FROM, --from=FROM"\
+    "-t TO, --to=TO"\
     "-v, --verbose"\
     "--help"\
     "--version"\
@@ -22,6 +25,8 @@ SCRIPT_OPTIONS=(\
 SCRIPT_OPTION_DESCRIPTIONS=(\
     "date format is YYYY-MM-DDThh:mm:ss"\
     ""\
+    "first revision (incl.)"\
+    "last revision (excl.)"\
     "explain what is being done"\
     "display this help and exit"\
     "output version information and exit"\
@@ -31,17 +36,17 @@ SCRIPT_EXAMPLES=(\
 )
 SCRIPT_SEE_ALSO=(\
     "git-logs(1)"\
-    "git-redate(1)"\
     "git-revision(1)"\
     "git-save(1)"\
 )
 
-### D E F A U L T   V A L U E S ###
+# # #   D E F A U L T   V A L U E S   # # #
 ORIGIN_HASH=$(commitHash HEAD)
+# # #   E N D   # # # # # # # # # # # # # #
 
 # We use "$@" instead of $* to preserve argument-boundary information
 # Add : to suppress getopt error messages, i.e. getopt -o ':...'
-ARGS=$(getopt -o 'd:m:v' --long 'date:,message:,verbose,help,version,update-manual' -- "$@") || { usage ; exit 1 ; }
+ARGS=$(getopt -o 'd:m:f:t:v' --long 'date:,message:,from:,to:,verbose,help,version,update-manual' -- "$@") || { usage ; exit 1 ; }
 eval "set -- $ARGS"
 
 while true; do
@@ -51,6 +56,12 @@ while true; do
             DATE=$2 ; shift 2 ;;
         (-m|--message)
             MESSAGE=$2 ; shift 2 ;;
+        (-f|--from)
+            isValidCommit "$2" || { error "revision does not exist" ; usage ; exit 1 ; }
+            FROM=$2 ; shift 2 ;;
+        (-t|--to)
+            isValidCommit "$2" || { error "revision does not exist" ; usage ; exit 1 ; }
+            TO=$2 ; shift 2 ;;
         (-v|--verbose)
             VERBOSE= ; shift ;;
         (--help)
@@ -68,18 +79,33 @@ done
 
 REMAINING_ARGS=("$@")
 
-main() {
-    if [[ ${#REMAINING_ARGS[@]} -ne 1 ]] ; then
-        error "required parameters not supplied" ; usage ; exit 1
-    fi
+# # #   H E L P   F U N C T I O N S   # # #
+originRevision() {
+    git reflog | grep "${ORIGIN_HASH:0:6}" | head -1 | awk '{ print substr($2, 0, length($2) - 1) }'
+}
 
-    local FT
-    IFS='..' read -ra FT <<< "${REMAINING_ARGS[0]}"
-    if [[ ${#FT[@]} -ne 3 || ! "${FT[0]}" =~ ^[1-9][0-9]*$ || ! "${FT[2]}" =~ ^[1-9][0-9]*$ ]] ; then
-        error "only positive integers" ; usage ; exit 1
-    fi
-    local FROM=${FT[0]}
-    local TO=${FT[2]}
+originStash() {
+    git stash list | grep origin_stash | awk -F: '{ print $1 }'
+}
+
+updatedOriginStash() {
+    git stash list | grep updated_origin_stash | awk -F: '{ print $1 }'
+}
+
+lastNonOriginStash() {
+    git stash list | grep -v origin_stash | head -1 | awk -F: '{ print $1 }'
+}
+
+numberOfStashes() {
+    git stash list | wc -l
+}
+# # #   E N D   # # # # # # # # # # # # # #
+
+main() {
+    ERRORS=()
+
+    : "${FROM:=0}"
+    : "${TO:=0}"
     local NUMBER_OF_REVISIONS=$(( TO - FROM ))
     if [[ $NUMBER_OF_REVISIONS -lt 1 || $NUMBER_OF_REVISIONS -gt $(( $(totalNumberOfCommits HEAD) - FROM )) ]] ; then
         error "wrong revision range" ; usage ; exit 1
@@ -92,57 +118,85 @@ main() {
 
     if [[ -z ${VERBOSE+set} ]] ; then
         exec 3>&1 4>&2 1>/dev/null 2>&1
-    fi &&\
+    fi
 
-    local COMMIT_MESSAGES=() &&\
-    local COMMIT_DATES=() &&\
-    STASHES=0 &&\ # GLOBAL VARIABLE
+    NUMBER_OF_STASHES_BEFORE=$(numberOfStashes)
+
+    if [[ -n $(git status --porcelain) ]] ; then
+        git stash push --all --message origin_stash
+    fi
+
+    local COMMIT_MESSAGES=()
+    local COMMIT_DATES=()
     for (( i = 0; i < FROM - 1; ++i )) ; do
-        COMMIT_MESSAGES[$i]=$(commitMessage HEAD) &&\
-        COMMIT_DATES[$i]=$(commitDate HEAD) &&\
-        git reset --soft HEAD~1 &&\
-        git stash && STASHES=$(( STASHES + 1 ))
-    done &&\
+        COMMIT_MESSAGES[$i]=$(commitMessage HEAD)
+        COMMIT_DATES[$i]=$(commitDate HEAD)
+        git reset --soft HEAD~1
+        git stash push --all
+    done
 
-    : "${DATE:="$(commitDate HEAD)"}" &&\
-    : "${MESSAGE:="$(commitMessage HEAD)"}" &&\
+    : "${DATE:=$(commitDate HEAD)}"
+    : "${MESSAGE:=$(commitMessage HEAD)}"
+    : "${FILE:=${REMAINING_ARGS[@]}}"
 
-    git reset --soft HEAD~"$NUMBER_OF_REVISIONS" &&\
-    git revision --date "$DATE" "$MESSAGE" &&\
+    git reset --soft HEAD~"$NUMBER_OF_REVISIONS"
+    git revision --verbose --date "$DATE" "$MESSAGE"
+
+    if [[ -n $(originStash) && -n ${FILE[*]} ]] ; then
+        git stash apply "$(originStash)" || { ERRORS+=("file had been created at later revision") ; return 1 ; }
+        git revision --verbose --amend --no-auto-indexing --date "$DATE" "$MESSAGE" "$FILE"
+        git stash push --all --message updated_origin_stash
+    fi
 
     for (( i = FROM - 2; i >= 0; --i )) ; do
-        git stash pop && STASHES=$(( STASHES - 1 )) &&\
-        git revision --date "${COMMIT_DATES[$i]}" "${COMMIT_MESSAGES[$i]}"
-    done &&\
+        git stash pop "$(lastNonOriginStash)"
+        git revision --verbose --date "${COMMIT_DATES[$i]}" "${COMMIT_MESSAGES[$i]}"
+    done
+
+    if [[ -n $(updatedOriginStash) ]] ; then
+        git stash pop "$(updatedOriginStash)"
+    elif [[ -n $(originStash) ]] ; then
+        git stash pop "$(originStash)"
+    fi
 
     if [[ -z ${VERBOSE+set} ]] ; then
         exec 1>&3 2>&4
-    fi &&\
+    fi
 
     for REVISION in "${JOINED_REVISIONS[@]}" ; do
         printf "%s\n" "$REVISION"
     done
-    printf "* * * REVISIONS JOINED AS FOLLOWS: * * *\n\n" &&\
+    printf "* * * REVISIONS JOINED AS FOLLOWS: * * *\n\n"
     git logs --number "$FROM"
 }
 
 recover() {
-    for (( i = 0 ; i < STASHES; ++i )) {
-        git stash pop
-    }
+    # Reset the index, but not the working tree (i.e., the changed files are preserved but not marked for commit)
+    git reset "$(originRevision)" --
+    git stash push --all
 
-    local REFLOG_HEAD
-    REFLOG_HEAD=$(git reflog | grep "${ORIGIN_HASH:0:6}" | head -1 | awk '{ print substr($2, 0, length($2) - 1) }')
-    : "${STASHES:=0}"
-    git reset "$REFLOG_HEAD" --
+    # Remove any dangling stashes and apply (if any) unstaged changes/untracked files
+    if [[ -n "$(updatedOriginStash)" ]] ; then
+        git stash drop "$(updatedOriginStash)"
+    fi
+
+    if [[ -n "$(originStash)" ]] ; then
+        git stash pop "$(originStash)" || ERRORS+=("no origin stash entry")
+    fi
+
+    NUMBER_OF_STASHES_AFTER=$(numberOfStashes)
+    for (( i = 0; i < NUMBER_OF_STASHES_AFTER - NUMBER_OF_STASHES_BEFORE; ++i )) {
+        git stash drop
+    }
 
     if [[ -z ${VERBOSE+set} ]] ; then
         exec 1>&3 2>&4
-    fi &&\
+    fi
 
+    for ERROR_MESSAGE in "${ERRORS[@]}" ; do
+        error "$ERROR_MESSAGE"
+    done
     error "recovered at $ORIGIN_HASH" ; usage ; exit 1
 }
 
-trap recover SIGINT
-
-main || recover
+trap recover SIGINT ERR && main
diff --git a/git-save b/git-save
--- a/git-save
+++ b/git-save
@@ -3,13 +3,14 @@
 # shellcheck disable=SC1091,SC2034
 
 set -o errexit
+set -o errtrace
 set -o nounset
 set -o pipefail
 
 . bash_template.sh
 . fs4git.sh
 
-SCRIPT_DESCRIPTION="update current revision"
+SCRIPT_DESCRIPTION="update current (or past) revision"
 SCRIPT_FULL_DESCRIPTION="-"
 SCRIPT_ARGUMENTS="[OPTION]... [FILE]..."
 SCRIPT_OPTIONS=(\
@@ -17,6 +18,7 @@ SCRIPT_OPTIONS=(\
     "--then"\
     "-d DATE, --date=DATE"\
     "-m MESSAGE, --message=MESSAGE"\
+    "-r REVISION, --revision=REVISION"\
     "-v, --verbose"\
     "--help"\
     "--version"\
@@ -25,7 +27,7 @@ SCRIPT_OPTION_DESCRIPTIONS=(\
     "current date, default"\
     "last revision date"\
     "date format is YYYY-mm-ddTHH:MM:SS"\
-    "date format is YYYY-mm-ddTHH:MM:SS"\
+    ""\
     ""\
     "explain what is being done"\
     "display this help and exit"\
@@ -37,16 +39,16 @@ SCRIPT_EXAMPLES=(\
 SCRIPT_SEE_ALSO=(\
     "git-join(1)"\
     "git-logs(1)"\
-    "git-redate(1)"\
     "git-revision(1)"\
 )
 
-### D E F A U L T   V A L U E S ###
+# # #   D E F A U L T   V A L U E S   # # #
 ORIGIN_HASH=$(commitHash HEAD)
+# # #   E N D   # # # # # # # # # # # # # #
 
 # We use "$@" instead of $* to preserve argument-boundary information
 # Add : to suppress getopt error messages, i.e. getopt -o ':...'
-ARGS=$(getopt -o 'd:m:v' --long 'now,then,date:,message:,verbose,help,version,update-manual' -- "$@") || { usage ; exit 1 ; }
+ARGS=$(getopt -o 'd:m:r:v' --long 'now,then,date:,message:,revision:,verbose,help,version,update-manual' -- "$@") || { usage ; exit 1 ; }
 eval "set -- $ARGS"
 
 while true; do
@@ -60,6 +62,11 @@ while true; do
             DATE=$2 ; shift 2 ;;
         (-m|--message)
             MESSAGE=$2 ; shift 2 ;;
+        (-r|--revision)
+            isValidCommit "$2" || { error "revision does not exist" ; usage ; exit 1 ; }
+            : "${DATE:=$(commitDate "$2")}"
+            : "${MESSAGE:=$(commitMessage "$2")}"
+            REVISION=$2 ; shift 2 ;;
         (-v|--verbose)
             VERBOSE= ; shift ;;
         (--help)
@@ -77,52 +84,54 @@ done
 
 REMAINING_ARGS=("$@")
 
+# # #   H E L P   F U N C T I O N S   # # #
+originRevision() {
+    git reflog | grep "${ORIGIN_HASH:0:6}" | head -1 | awk '{ print substr($2, 0, length($2) - 1) }'
+}
+# # #   E N D   # # # # # # # # # # # # # #
+
 main() {
+    ERRORS=()
+
     if [[ -z ${VERBOSE+set} ]] ; then
         exec 3>&1 4>&2 1>/dev/null 2>&1
-    fi &&\
+    fi
 
-    FILE=("${REMAINING_ARGS[@]}") &&\
-    if [[ -n ${FILE[*]} ]] ; then
-        git add -- "${FILE[@]}" || { error "file does not exist" ; return 1 ; }
+    : "${DATE:=$(date +%Y-%m-%dT%H:%M:%S --date now)}"
+    : "${MESSAGE:=$(commitMessage "$ORIGIN_HASH")}"
+    : "${REVISION:=1}"
+    : "${FILE:=${REMAINING_ARGS[@]}}"
+
+    local UPDATED_REVISION
+    UPDATED_REVISION="$(git logs --hash "$(commitHash "$REVISION")")"
+
+    if [[ $REVISION -eq 1 ]] ; then
+        git revision --verbose --amend --date "$DATE" "$MESSAGE" "$FILE" || { ERRORS+=("git revision error") ; return 1 ; }
     else
-        git add -A
-    fi &&\
-
-    export GIT_AUTHOR_DATE=${DATE-$(date +%Y-%m-%dT%H:%M:%S --date now)} &&\
-    export GIT_COMMITTER_DATE=${DATE-$(date +%Y-%m-%dT%H:%M:%S --date now)} &&\
-    git commit -S -s -m "${MESSAGE-$(commitMessage "$ORIGIN_HASH")}" --reset-author --amend --no-edit &&\
+        git join --verbose --date "$DATE" --message "$MESSAGE" --from "$REVISION" --to "$(( REVISION + 1 ))" "${FILE:=.}" || { ERRORS+=("git join error") ; return 1 ; }
+    fi
 
     if [[ -z ${VERBOSE+set} ]] ; then
         exec 1>&3 2>&4
-    fi &&\
+    fi
 
-    printf "%s\n" "$(git logs --hash "$ORIGIN_HASH")"
-    printf "* * * LAST REVISION UPDATED AS FOLLOWS * * *\n\n" &&\
-    git logs --hash HEAD
+    printf "%s\n" "$UPDATED_REVISION"
+    printf "* * * #%d REVISION UPDATED AS FOLLOWS * * *\n\n" "$REVISION"
+    git logs --hash "$REVISION"
 }
 
 recover() {
-    export GIT_AUTHOR_DATE=
-    export GIT_COMMITTER_DATE=
-
-    local REFLOG_HEAD
-    REFLOG_HEAD=$(git reflog | grep "${ORIGIN_HASH:0:6}" | head -1 | awk '{ print substr($2, 0, length($2) - 1) }')
-    git reset "$REFLOG_HEAD" --
-
-    if [[ -n ${FILE[*]} ]] ; then
-        git restore --staged -- "${FILE[@]}" || { error "file does not exist" ; }
-    else
-        git restore --staged -- .
-    fi
+    # Reset the index, but not the working tree (i.e., the changed files are preserved but not marked for commit)
+    git reset "$(originRevision)" --
 
     if [[ -z ${VERBOSE+set} ]] ; then
         exec 1>&3 2>&4
     fi
 
+    for ERROR_MESSAGE in "${ERRORS[@]}" ; do
+        error "$ERROR_MESSAGE"
+    done
     error "recovered at $ORIGIN_HASH" ; usage ; exit 1
 }
 
-trap recover SIGINT
-
-main || recover
+trap recover SIGINT ERR && main
