Upgrade main git-scripts
Signed-off-by: mimly <m.j.mlynczak@gmail.com>

diff --git a/git-join b/git-join
--- a/git-join
+++ b/git-join
@@ -1,55 +1,146 @@
 #!/bin/bash
 
-source fs4git.sh
+# shellcheck disable=SC1091,SC2034
 
-if [[ $# -eq 2 ]] ; then
-    numberOfRevisions=$1
-    message=$2
-    from=1
-elif [[ $# -eq 3 ]] ; then
-    numberOfRevisions=$1
-    message=$2
-    if [[ "$3" =~ ^[0-9]+$ ]] ; then
-        from=$3
-    else
-        from=1
-        date=$3
+set -o errexit
+set -o nounset
+set -o pipefail
+
+. bash_template.sh
+. fs4git.sh
+
+SCRIPT_NAME=$(basename "${0}")
+SCRIPT_VERSION="0.0.1"
+SCRIPT_AUTHOR="mimly"
+SCRIPT_GIT="https://github.com/mimly"
+SCRIPT_LICENSE="MIT"
+SCRIPT_DESCRIPTION="join revisions"
+SCRIPT_ARGUMENTS="[OPTION]... FROM..TO"
+SCRIPT_OPTIONS=(\
+    "-d DATE, --date=DATE"\
+    "-m MESSAGE, --message=MESSAGE"\
+    "-v, --verbose"\
+    "--help"\
+    "--version"\
+)
+SCRIPT_OPTION_DESCRIPTIONS=(\
+    "date format is YYYY-MM-DDThh:mm:ss"\
+    ""\
+    "explain what is being done"\
+    "display this help and exit"\
+    "output version information and exit"\
+)
+SCRIPT_EXAMPLES=(\
+    "2..4  # joins 2nd and 3rd revision with 2nd revisions date and message"\
+)
+
+### D E F A U L T   V A L U E S ###
+ORIGIN_HASH=$(commitHash HEAD)
+
+# We use "$@" instead of $* to preserve argument-boundary information
+# Add : to suppress getopt error messages, i.e. getopt -o ':...'
+ARGS=$(getopt -o 'd:m:v' --long 'date:,message:,verbose,help,version,update-manual' -- "$@") || { usage ; exit 1 ; }
+eval "set -- $ARGS"
+
+while true; do
+    case $1 in
+        (-d|--date)
+            isValidDate "$2" || { error "date format is YYYY-mm-ddTHH:MM:SS" ; usage ; exit 1 ; }
+            DATE=$2 ; shift 2 ;;
+        (-m|--message)
+            MESSAGE=$2 ; shift 2 ;;
+        (-v|--verbose)
+            VERBOSE= ; shift ;;
+        (--help)
+            usageFull ; exit 0 ;;
+        (--version)
+            about ; changelog ; exit 0 ;;
+        (--update-manual) # hidden option
+            updateManual ; exit 0 ;;
+        (--)
+            shift ; break ;;
+        (*)
+            usage ; exit 1 ;;
+    esac
+done
+
+REMAINING_ARGS=("$@")
+
+main() {
+    if [[ ${#REMAINING_ARGS[@]} -ne 1 ]] ; then
+        error "required parameters not supplied" ; usage ; exit 1
     fi
-elif [[ $# -eq 4 ]] ; then
-    numberOfRevisions=$1
-    message=$2
-    from=$3
-    date=$4
-else
-    printf "USAGE: git join <numberOfRevisions> <message> [<from=1>] [<date=then>]\n"
-    exit 1
-fi
 
-if [[ $numberOfRevisions -lt 1 || $numberOfRevisions -gt $(( $(totalNumberOfCommits HEAD) - from )) ]] ; then
-    printf "USAGE: git join <numberOfRevisions> <message> [<from=1>] [<date=then>]\n"
-    exit 1
-fi
+    local FT
+    IFS='..' read -ra FT <<< "${REMAINING_ARGS[0]}"
+    if [[ ${#FT[@]} -ne 3 || ! "${FT[0]}" =~ ^[1-9][0-9]*$ || ! "${FT[2]}" =~ ^[1-9][0-9]*$ ]] ; then
+        error "only positive integers" ; usage ; exit 1
+    fi
+    local FROM=${FT[0]}
+    local TO=${FT[2]}
+    local NUMBER_OF_REVISIONS=$(( TO - FROM ))
+    if [[ $NUMBER_OF_REVISIONS -lt 1 || $NUMBER_OF_REVISIONS -gt $(( $(totalNumberOfCommits HEAD) - FROM )) ]] ; then
+        error "wrong revision range" ; usage ; exit 1
+    fi
 
-declare -a commitMessages &&\
-declare -a commitDates &&\
+    local JOINED_REVISIONS=()
+    for HASH in $(git rev-list --abbrev-commit HEAD~$(( TO - 1 ))..HEAD~$(( FROM - 1 ))) ; do
+        JOINED_REVISIONS+=("$(git logs --hash "$HASH")")
+    done
 
-for (( i = 0; i < from - 1; ++i )) ; do
-    commitMessages[$i]=$(commitMessage HEAD) &&\
-    commitDates[$i]=$(commitDate HEAD) &&\
-    git reset --soft HEAD~1 &&\
-    git stash
-done &&\
+    if [[ -z ${VERBOSE+set} ]] ; then
+        exec 3>&1 4>&2 1>/dev/null 2>&1
+    fi &&\
 
-if [[ -z $date ]] ; then
-    date=$(commitDate HEAD)
-fi &&\
+    local COMMIT_MESSAGES=() &&\
+    local COMMIT_DATES=() &&\
+    STASHES=0 &&\ # GLOBAL VARIABLE
+    for (( i = 0; i < FROM - 1; ++i )) ; do
+        COMMIT_MESSAGES[$i]=$(commitMessage HEAD) &&\
+        COMMIT_DATES[$i]=$(commitDate HEAD) &&\
+        git reset --soft HEAD~1 &&\
+        git stash && STASHES=$(( STASHES + 1 ))
+    done &&\
 
-git reset --soft HEAD~"$numberOfRevisions" &&\
-git revision "$message" "$date" &&\
+    : "${DATE:="$(commitDate HEAD)"}" &&\
+    : "${MESSAGE:="$(commitMessage HEAD)"}" &&\
 
-for (( i = from - 2; i >= 0; --i )) ; do
-    git stash pop &&\
-    git revision "${commitMessages[$i]}" "${commitDates[$i]}"
-done &&\
+    git reset --soft HEAD~"$NUMBER_OF_REVISIONS" &&\
+    git revision --date "$DATE" "$MESSAGE" &&\
 
-printf "* * * THE LAST %d REVISIONS (FROM %d) JOINED * * *\n\n" "$numberOfRevisions" "$from"
+    for (( i = FROM - 2; i >= 0; --i )) ; do
+        git stash pop && STASHES=$(( STASHES - 1 )) &&\
+        git revision --date "${COMMIT_DATES[$i]}" "${COMMIT_MESSAGES[$i]}"
+    done &&\
+
+    if [[ -z ${VERBOSE+set} ]] ; then
+        exec 1>&3 2>&4
+    fi &&\
+
+    for REVISION in "${JOINED_REVISIONS[@]}" ; do
+        printf "%s\n" "$REVISION"
+    done
+    printf "* * * REVISIONS JOINED AS FOLLOWS: * * *\n\n" &&\
+    git logs --number "$FROM"
+}
+
+recover() {
+    for (( i = 0 ; i < STASHES; ++i )) {
+        git stash pop
+    }
+
+    local REFLOG_HEAD
+    REFLOG_HEAD=$(git reflog | grep "${ORIGIN_HASH:0:6}" | head -1 | awk '{ print substr($2, 0, length($2) - 1) }')
+    : "${STASHES:=0}"
+    git reset "$REFLOG_HEAD" --
+
+    if [[ -z ${VERBOSE+set} ]] ; then
+        exec 1>&3 2>&4
+    fi &&\
+
+    error "recovered at $ORIGIN_HASH" ; usage ; exit 1
+}
+
+trap recover SIGINT
+
+main || recover
diff --git a/git-redate b/git-redate
--- a/git-redate
+++ b/git-redate
@@ -1,25 +1,114 @@
 #!/bin/bash
 
-source fs4git.sh
+# shellcheck disable=SC1091,SC2034
 
-if [[ $# -eq 2 ]] ; then
-    revision=$1
-    date=$2
-    message=$(commitMessage "$(commitHash "$revision")")
-elif [[ $# -eq 3 ]] ; then
-    revision=$1
-    date=$2
-    message=$3
-else
-    printf "USAGE: git redate <revision> <date> [<message=same>]\n"
-    exit 1
-fi
+set -o errexit
+set -o nounset
+set -o pipefail
 
-if [[ $revision -lt 1 || $(totalNumberOfCommits HEAD) -le 1 || $revision -ge $(totalNumberOfCommits HEAD) ]] || ! isValidDate "$date" ; then
-    printf "USAGE: git redate <revision> <date> [<message=same>]\n"
-    exit 1
-fi
+. bash_template.sh
+. fs4git.sh
 
-git join 1 "$message" "$revision" "$date" >/dev/null 2>&1 &&\
-printf "\n\n* * * #%d REVISION REDATED AT \"%s\" * * *\n\n" "$revision" "$date" &&\
-git logs "$revision"
+SCRIPT_NAME=$(basename "${0}")
+SCRIPT_VERSION="0.0.1"
+SCRIPT_AUTHOR="mimly"
+SCRIPT_GIT="https://github.com/mimly"
+SCRIPT_LICENSE="MIT"
+SCRIPT_DESCRIPTION="modify old revision"
+SCRIPT_ARGUMENTS="[OPTION]... REVISION"
+SCRIPT_OPTIONS=(\
+    "-d DATE, --date=DATE"\
+    "-m MESSAGE, --message=MESSAGE"\
+    "-v, --verbose"\
+    "--help"\
+    "--version"\
+)
+SCRIPT_OPTION_DESCRIPTIONS=(\
+    "date format is YYYY-mm-ddTHH:MM:SS"\
+    ""\
+    "explain what is being done"\
+    "display this help and exit"\
+    "output version information and exit"\
+)
+SCRIPT_EXAMPLES=(\
+    "REVISION"\
+)
+
+### D E F A U L T   V A L U E S ###
+ORIGIN_HASH=$(commitHash HEAD)
+
+# We use "$@" instead of $* to preserve argument-boundary information
+# Add : to suppress getopt error messages, i.e. getopt -o ':...'
+ARGS=$(getopt -o 'd:m:v' --long 'date:,message:,verbose,help,version,update-manual' -- "$@") || { usage ; exit 1 ; }
+eval "set -- $ARGS"
+
+while true; do
+    case $1 in
+        (-d|--date)
+            isValidDate "$2" || { error "date format is YYYY-mm-ddTHH:MM:SS" ; usage ; exit 1 ; }
+            DATE=$2 ; shift 2 ;;
+        (-m|--message)
+            MESSAGE=$2 ; shift 2 ;;
+        (-v|--verbose)
+            VERBOSE= ; shift ;;
+        (--help)
+            usageFull ; exit 0 ;;
+        (--version)
+            about ; changelog ; exit 0 ;;
+        (--update-manual) # hidden option
+            updateManual ; exit 0 ;;
+        (--)
+            shift ; break ;;
+        (*)
+            usage ; exit 1 ;;
+    esac
+done
+
+REMAINING_ARGS=("$@")
+
+main() {
+    if [[ ${#REMAINING_ARGS[@]} -ne 1 ]] ; then
+        error "required parameters not supplied" ; usage ; exit 1
+    fi
+    local REVISION=${REMAINING_ARGS[0]}
+
+    if ! isValidCommit "$REVISION" ; then
+        error "revision does not exist" ; usage ; exit 1
+    fi
+
+    : "${HASH:=$(commitHash "$REVISION")}"
+    local MODIFIED_REVISION
+    MODIFIED_REVISION="$(git logs --hash "$HASH")"
+    : "${DATE:=$(commitDate "$REVISION")}"
+    : "${MESSAGE:=$(commitMessage "$REVISION")}"
+
+    if [[ -z ${VERBOSE+set} ]] ; then
+        exec 3>&1 4>&2 1>/dev/null 2>&1
+    fi &&\
+
+    git join --date "$DATE" --message "$MESSAGE" "$REVISION..$(( REVISION + 1 ))" &&\
+
+    if [[ -z ${VERBOSE+set} ]] ; then
+        exec 1>&3 2>&4
+    fi &&\
+
+    printf "%s\n" "$MODIFIED_REVISION"
+    printf "* * * REVISION MODIFIED AS FOLLOWS: * * *\n\n" &&\
+    git logs --number "$REVISION"
+}
+
+recover() {
+    local REFLOG_HEAD
+    REFLOG_HEAD=$(git reflog | grep "${ORIGIN_HASH:0:6}" | head -1 | awk '{ print substr($2, 0, length($2) - 1) }')
+    git reset "$REFLOG_HEAD" --
+
+    if [[ -z ${VERBOSE+set} ]] ; then
+        exec 1>&3 2>&4
+    fi
+
+    error "recovered at $ORIGIN_HASH" ; usage ; exit 1
+}
+
+trap recover SIGINT
+
+main || recover
diff --git a/git-revision b/git-revision
--- a/git-revision
+++ b/git-revision
@@ -1,25 +1,117 @@
 #!/bin/bash
 
-source fs4git.sh
+# shellcheck disable=SC1091,SC2034
 
-if [[ $# -eq 1 ]] ; then
-    message=$1
-    git add -A
-elif [[ $# -ge 2 ]] ; then
-    message=$1
-    if isValidDate "$2" >/dev/null 2>&1 ; then
-        export GIT_AUTHOR_DATE=$2
-        export GIT_COMMITTER_DATE=$2
-        git add -A
-    else
-        shift 1
-        git add "$@" || exit 1 # file not exist
+set -o errexit
+set -o nounset
+set -o pipefail
+
+. bash_template.sh
+. fs4git.sh
+
+SCRIPT_NAME=$(basename "${0}")
+SCRIPT_VERSION="0.0.1"
+SCRIPT_AUTHOR="mimly"
+SCRIPT_GIT="https://github.com/mimly"
+SCRIPT_LICENSE="MIT"
+SCRIPT_DESCRIPTION="make new revision"
+SCRIPT_ARGUMENTS="[OPTION]... MESSAGE [FILE]..."
+SCRIPT_OPTIONS=(\
+    "-d DATE, --date=DATE"\
+    "-v, --verbose"\
+    "--help"\
+    "--version"\
+)
+SCRIPT_OPTION_DESCRIPTIONS=(\
+    "date format is YYYY-mm-ddTHH:MM:SS"\
+    "explain what is being done"\
+    "display this help and exit"\
+    "output version information and exit"\
+)
+SCRIPT_EXAMPLES=(\
+    "MESSAGE"\
+)
+
+### D E F A U L T   V A L U E S ###
+ORIGIN_HASH=$(commitHash HEAD || echo "no commits yet")
+
+# We use "$@" instead of $* to preserve argument-boundary information
+# Add : to suppress getopt error messages, i.e. getopt -o ':...'
+ARGS=$(getopt -o 'd:v' --long 'date:,verbose,help,version,update-manual' -- "$@") || { usage ; exit 1 ; }
+eval "set -- $ARGS"
+
+while true; do
+    case $1 in
+        (-d|--date)
+            isValidDate "$2" || { error "date format is YYYY-mm-ddTHH:MM:SS" ; usage ; exit 1 ; }
+            export GIT_AUTHOR_DATE=$2
+            export GIT_COMMITTER_DATE=$2
+            shift 2 ;;
+        (-v|--verbose)
+            VERBOSE= ; shift ;;
+        (--help)
+            usageFull ; exit 0 ;;
+        (--version)
+            about ; changelog ; exit 0 ;;
+        (--update-manual) # hidden option
+            updateManual ; exit 0 ;;
+        (--)
+            shift ; break ;;
+        (*)
+            usage ; exit 1 ;;
+    esac
+done
+
+REMAINING_ARGS=("$@")
+
+main() {
+    if [[ ${#REMAINING_ARGS[@]} -lt 1 ]] ; then
+        error "required parameters not supplied" ; usage ; exit 1
     fi
-else
-    printf "USAGE: git revision <message> [<date=now>] OR git revision <message> [<file(s)=all>]\n"
-    exit 1
-fi
+    local MESSAGE=${REMAINING_ARGS[0]}
 
-git commit -S -s -m "$message" &&\
-printf "\n\n* * * NEW REVISION DONE * * *\n\n" &&\
-git logs 1
+    if [[ -z ${VERBOSE+set} ]] ; then
+        exec 3>&1 4>&2 1>/dev/null 2>&1
+    fi &&\
+
+    FILE=("${REMAINING_ARGS[@]:1}") &&\
+    if [[ -n ${FILE[*]} ]] ; then
+        git add -- "${FILE[@]}" || { error "file does not exist" ; return 1 ; }
+    else
+        git add -A
+    fi &&\
+
+    git commit -S -s -m "$MESSAGE" &&\
+
+    if [[ -z ${VERBOSE+set} ]] ; then
+        exec 1>&3 2>&4
+    fi &&\
+
+    printf "* * * NEW REVISION DONE * * *\n\n" &&\
+    git logs --hash HEAD
+}
+
+recover() {
+    export GIT_AUTHOR_DATE=
+    export GIT_COMMITTER_DATE=
+
+    local REFLOG_HEAD
+    REFLOG_HEAD=$(git reflog | grep "${ORIGIN_HASH:0:6}" | head -1 | awk '{ print substr($2, 0, length($2) - 1) }')
+    git reset "$REFLOG_HEAD" --
+
+    if [[ -n ${FILE[*]} ]] ; then
+        git restore --staged -- "${FILE[@]}" || { error "file does not exist" ; }
+    else
+        git restore --staged -- .
+    fi
+
+    if [[ -z ${VERBOSE+set} ]] ; then
+        exec 1>&3 2>&4
+    fi
+
+    error "recovered at $ORIGIN_HASH" ; usage ; exit 1
+}
+
+trap recover SIGINT
+
+main || recover
